[package]
name = "linter"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
argh = "0.1.13"
# The version on crates.io is outdated, so we fetch from github instead
# FIXME: use upstream repo instead once https://github.com/KyleMayes/clang-rs/pull/60 is merged
clang = { git = "https://github.com/pstiasny/clang-rs.git", branch = "master", version = "2.0.0", features = ["runtime", "clang_10_0"] }
colorize = "0.1.0"
